name: Deploy Node JS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PUBLISH_URL: ${{ secrets.LIN_CLOUD_URL_240 }}
  PUBLISH_KEY: ${{ secrets.LIN_CLOUD_KEY_240 }}
  ZIP_NAME: app.zip

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # --------------------
      # Checkout
      # --------------------
      - name: Checkout
        uses: actions/checkout@v4

      # --------------------
      # Zip dist
      # --------------------
      - name: Zip project folder
        run: |
          # Creamos el zip excluyendo el propio zip, node_modules y otros archivos innecesarios
          zip -r ${{ env.ZIP_NAME }} . -x "node_modules/*" ".git/*" ".env" "${{ env.ZIP_NAME }}" "test-db.js"

      # --------------------
      # Verify File
      # --------------------
      - name: Verify ZIP existence
        run: |
          if [ -f "${{ env.ZIP_NAME }}" ]; then
            echo "✅ ${{ env.ZIP_NAME }} creado con éxito."
            ls -lh ${{ env.ZIP_NAME }}
          else
            echo "❌ Error: ${{ env.ZIP_NAME }} no se encuentra."
            exit 1
          fi

      # --------------------
      # Deploy
      # --------------------
      - name: Upload ZIP a LIN Cloud IIS Push
        run: |
          curl -v -X POST \
            "$PUBLISH_URL/api/Publish?createRelease=true" \
            -H "accept: text/plain" \
            -H "Content-Type: multipart/form-data" \
            -H "Key: $PUBLISH_KEY" \
            -F "file=@${{ env.ZIP_NAME }}"
